In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df=pd.read_csv("housing.csv")
df

town  area   price  Unnamed: 3
0   monroe township  2600  550000         NaN
1   monroe township  3000  565000         NaN
2   monroe township  3200  610000         NaN
3   monroe township  3600  680000         NaN
4   monroe township  4000  725000         NaN
5      west windsor  2600  585000         NaN
6      west windsor  2800  615000         NaN
7      west windsor  3300  650000         NaN
8      west windsor  3600  710000         NaN
9       robinsville  2600  575000         NaN
10      robinsville  2900  600000         NaN
11      robinsville  3100  620000         NaN
12      robinsville  3600  695000         NaN

In [5]:
df=df.dropna(how='all',axis=1)

In [6]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [7]:
dummies=pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [8]:
merged=pd.concat([df,dummies],axis=1)
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [9]:
final=merged.drop(['town','monroe township'],axis=1)

In [10]:
final

area   price  robinsville  west windsor
0   2600  550000            0             0
1   3000  565000            0             0
2   3200  610000            0             0
3   3600  680000            0             0
4   4000  725000            0             0
5   2600  585000            0             1
6   2800  615000            0             1
7   3300  650000            0             1
8   3600  710000            0             1
9   2600  575000            1             0
10  2900  600000            1             0
11  3100  620000            1             0
12  3600  695000            1             0

In [11]:
rg=linear_model.LinearRegression()

In [14]:
rg.fit(final[['area','robinsville','west windsor']],final.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
rg.predict([[2800,1,0]])

array([590775.63964739])

In [17]:
rg.predict([[3400,0,1]])

array([681241.6684584])

In [18]:
rg.score(final[['area','robinsville','west windsor']],final.price) #to test how accurate our model is

0.9573929037221871

In [12]:
#an alternate way to supply the rows and columns
X=final.drop('price',axis=1)
X

area  robinsville  west windsor
0   2600            0             0
1   3000            0             0
2   3200            0             0
3   3600            0             0
4   4000            0             0
5   2600            0             1
6   2800            0             1
7   3300            0             1
8   3600            0             1
9   2600            1             0
10  2900            1             0
11  3100            1             0
12  3600            1             0

In [13]:
Y=final.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [26]:
rg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
rg.predict([[2800,1,0]])

array([590775.63964739])

In [24]:
rg.predict([[3400,0,1]])

array([681241.6684584])

In [27]:
rg.score(X,Y)

0.9573929037221871

In [25]:
#Using sklearn One Hot Encoder

In [28]:
#in sklearn to do One Hot Encoding you would have to label the column on which you want to do it

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le=LabelEncoder()

In [17]:
le.fit_transform(df.town)

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [18]:
df.town=le.fit_transform(df.town)
df

C:\Users\KIIT\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [19]:
X=df[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [20]:
Y=df.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [21]:
#to create dummy variable columns 

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe=ColumnTransformer([("town",OneHotEncoder(),[0])],remainder='passthrough')

In [24]:
X=ohe.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [25]:
X=X[:,1:] #to avoid dummy variable trap, drop a column
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [26]:
rg.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
rg.predict([[1,0,2800]])

array([590775.63964739])